### PR TITLE
Append 'noplugin' to context buffer filetype

### PR DESCRIPTION
**Pull request by midchildan**
This would make it easier to disable filetype-based plugins such as linting and completion.

### CODE REVIEW

**Comment by wellle** [comment]
Hmm. I'm not sure I understand what's happening here. To me it looks like this just breaks highlighting completely in the context window, doesn't it?

So for example if I'm working on C code, my main buffer's filetype will be `c`. With this change added the preview window's filetype will be set to `cnoplugin`, right? So I won't get any C highlighting.

If that would be the intended effect, we might as well not set the filetype at all. But to me it seems like code highlighting seems attractive here.

What do you think?

**Comment by midchildan** [comment]
Sorry, I forgot to put a single dot. I've fixed it so that it works without breaking syntax highlighting.

[This](https://vimhelp.org/options.txt.html#%27filetype%27) explains how it works:
> When a dot appears in the value then this separates two filetype names.  Example:
> /* vim: set filetype=c.doxygen : */ 
> This will use the "c" filetype first, then the "doxygen" filetype. This works both for filetype plugins and for syntax files.  More than one dot may appear.

**Comment by wellle** [comment]
Thank you, that's more clear now!

Why `noplugin` though, is that some sort of convention?

If not, maybe we might add something like `.contextvim` instead?

**Comment by midchildan** [comment]
It's not a convention, but I thought it would make the intention more clear and would help avoid duplication of similar configurations. I'm totally fine with `contextvim`, though :-)

**Comment by wellle** [comment]
Okay thanks. I'm fine with `noplugin` too, merged 👍

**Pull request merged**
